version: '3.3'
services:
    dockupdater:
        container_name: dockupdater
        environment:
            - CLEANUP=true
            - RUN_ONCE=true
            - LOG_LEVEL=info
            - LABEL=true
            - WAIT=180
            - SKIP_START_NOTIF=true
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        image: dockupdater/dockupdater

networks:
  proxy:
    driver: bridge
    external: true
